const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('../.runtime/tools/node_modules/playwright');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.txt':'text/plain'};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(!pathname.startsWith('/Sketch-Analysis/')){res.writeHead(404);res.end();return;}const relative=pathname.slice('/Sketch-Analysis/'.length)||'index.html',file=path.resolve(__dirname,'docs',relative);if(!file.startsWith(path.resolve(__dirname,'docs')+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(file,(err,body)=>{res.writeHead(err?404:200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(err?'Not found':body);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port+'/Sketch-Analysis/';
 await page.goto(base);await page.locator('.card').first().waitFor({timeout:180000});assert.equal(await page.locator('.card').count(),48);await page.locator('#ink-chart svg').waitFor({timeout:180000});console.log('PASS real Google category download, persistent browser cache, full histogram');
 await page.locator('#average-button').click();await page.locator('#average-image').waitFor({state:'visible'});await page.locator('#average-interpret').click();await page.keyboard.press('Escape');
 await page.goto(base+'animate.html');await page.waitForFunction(()=>!document.getElementById('play').disabled);await page.locator('#heatmap').check();await page.locator('#next-drawing').click();await page.waitForFunction(()=>document.getElementById('position').textContent.includes('Drawing 2 of'));console.log('PASS average, interpretation, animation and heatmap');
 await page.goto(base+'analysis.html');await page.waitForFunction(()=>document.querySelectorAll('#analysis-category option').length===345);await page.locator('#run-analysis').click();await page.locator('.analysis-section').first().waitFor({timeout:180000});assert.equal(await page.locator('.analysis-section').count(),9);await page.getByRole('button',{name:'US',exact:true}).click();await page.locator('#country-images canvas').first().waitFor();assert.equal(await page.locator('#country-images canvas').count(),48);console.log('PASS full browser analysis and country gallery');
 await page.goto(base+'draw.html');await page.waitForFunction(()=>document.getElementById('match-status').textContent.includes('Ready'),{},{timeout:60000});const box=await page.locator('#sketch').boundingBox();await page.mouse.move(box.x+30,box.y+30);await page.mouse.down();await page.mouse.move(box.x+120,box.y+150,{steps:10});await page.mouse.up();await page.locator('#match-image svg').waitFor();console.log('PASS browser matching worker');
 await page.goto(base+'histograms.html');await page.locator('.category-histogram').first().waitFor();assert.equal(await page.locator('.category-histogram').count(),345);await page.locator('#histogram-search').fill('cat');await page.locator('.category-histogram svg').first().waitFor({timeout:60000});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS all histograms and mobile layout without a Node API');
 }finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
